package com.example.deflate.security

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import com.google.gson.Gson
import java.nio.charset.Charset
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec


interface CryptographyManager {

    fun getInitializedCipherForEncryption(keyName: String): Cipher

    fun getInitializedCipherForDecryption(keyName: String, initializationVector: ByteArray): Cipher

    /**
     * The Cipher created with [getInitializedCipherForEncryption] is used here
     */
    fun encryptData(plaintext: String, cipher: Cipher): CiphertextWrapper

    /**
     * The Cipher created with [getInitializedCipherForDecryption] is used here
     */
    fun decryptData(ciphertext: ByteArray, cipher: Cipher): String

    fun persistCiphertextWrapperToSharedPrefs(
        ciphertextWrapper: CiphertextWrapper,
        context: Context,
        filename: String,
        mode: Int,
        prefKey: String
    )

    fun getCiphertextWrapperFromSharedPrefs(
        context: Context,
        filename: String,
        mode: Int,
        prefKey: String
    ): CiphertextWrapper?
}

// Factory function to obtain implementation
fun CryptographyManager(): CryptographyManager = CryptographyManagerImpl()

// Private implementation
private class CryptographyManagerImpl : CryptographyManager {

    // AES/GCM parameters
    private val KEY_SIZE_BITS = 256
    private val ANDROID_KEYSTORE = "AndroidKeyStore"
    private val BLOCK_MODE = KeyProperties.BLOCK_MODE_GCM
    private val PADDING = KeyProperties.ENCRYPTION_PADDING_NONE
    private val ALGORITHM = KeyProperties.KEY_ALGORITHM_AES
    private val TRANSFORMATION = "$ALGORITHM/$BLOCK_MODE/$PADDING"

    override fun getInitializedCipherForEncryption(keyName: String): Cipher {
        // Create cipher and init with a SecretKey (auto-generated if missing)
        val cipher = getCipher()
        val secretKey = getOrCreateSecretKey(keyName)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)
        return cipher
    }

    override fun getInitializedCipherForDecryption(keyName: String, initializationVector: ByteArray): Cipher {
        val cipher = getCipher()
        val secretKey = getOrCreateSecretKey(keyName)
        // GCM tag length 128 bits (recommended)
        cipher.init(Cipher.DECRYPT_MODE, secretKey, GCMParameterSpec(128, initializationVector))
        return cipher
    }

    override fun encryptData(plaintext: String, cipher: Cipher): CiphertextWrapper {
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charset.forName("UTF-8")))
        // Cipher.iv is the initialization vector generated by cipher.init
        return CiphertextWrapper(cipherText = ciphertext, initializationVector = cipher.iv)
    }

    override fun decryptData(ciphertext: ByteArray, cipher: Cipher): String {
        val plaintext = cipher.doFinal(ciphertext)
        return String(plaintext, Charset.forName("UTF-8"))
    }

    private fun getCipher(): Cipher = Cipher.getInstance(TRANSFORMATION)

    /**
     * Get existing key from AndroidKeyStore or create a new AES key with:
     *  - AES/GCM/NoPadding
     *  - Key size 256
     *  - PURPOSE_ENCRYPT | PURPOSE_DECRYPT
     *  - setUserAuthenticationRequired(true) -> requires biometric/credential before use
     *
     * Important: setUserAuthenticationRequired(true) will cause the system to require authentication to use the key.
     * If you want the key to be usable for some seconds after auth (no prompt each call), set
     * setUserAuthenticationValidityDurationSeconds(n) to a positive integer instead of 0.
     */
    private fun getOrCreateSecretKey(keyName: String): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE)
        keyStore.load(null)

        // If a key for keyName already exists this method returns it
        keyStore.getKey(keyName, null)?.let {
            return it as SecretKey
        }

        // If it is not present we generate a new AES key inside the AndroidKeyStore
        val keyGen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        val builder = KeyGenParameterSpec.Builder(
            keyName,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        ).apply {
            setBlockModes(BLOCK_MODE)
            setEncryptionPaddings(PADDING)
            setKeySize(KEY_SIZE_BITS)
            // Require user authentication for using the key biometric or device credential
            setUserAuthenticationRequired(true)

        }

        keyGen.init(builder.build())
        return keyGen.generateKey()
    }

    override fun persistCiphertextWrapperToSharedPrefs(
        ciphertextWrapper: CiphertextWrapper,
        context: Context,
        filename: String,
        mode: Int,
        prefKey: String
    ) {
        val json = Gson().toJson(ciphertextWrapper)
        context.getSharedPreferences(filename, mode).edit().putString(prefKey, json).apply()
    }

    override fun getCiphertextWrapperFromSharedPrefs(
        context: Context,
        filename: String,
        mode: Int,
        prefKey: String
    ): CiphertextWrapper? {
        val json = context.getSharedPreferences(filename, mode).getString(prefKey, null) ?: return null
        return Gson().fromJson(json, CiphertextWrapper::class.java)
    }
}




